// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6R_JsaJ8Tl1OjFXb8zZlGKT5gjaWSIgc',
    appId: '1:59202183466:web:4916c23fed06158bf1be53',
    messagingSenderId: '59202183466',
    projectId: 'proyect-desfc',
    authDomain: 'proyect-desfc.firebaseapp.com',
    storageBucket: 'proyect-desfc.firebasestorage.app',
    measurementId: 'G-62BF5NZXG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPjsE4Y2dmzHwW37hYJ50wdEIWKohnR30',
    appId: '1:59202183466:android:98fdd4aa86cea5acf1be53',
    messagingSenderId: '59202183466',
    projectId: 'proyect-desfc',
    storageBucket: 'proyect-desfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXp7vEvkQMMh06Hf2JZLi7YaoiTpLCrc',
    appId: '1:59202183466:ios:56daa36a7518c0fcf1be53',
    messagingSenderId: '59202183466',
    projectId: 'proyect-desfc',
    storageBucket: 'proyect-desfc.firebasestorage.app',
    iosBundleId: 'com.example.projectDesarrolladoresfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXp7vEvkQMMh06Hf2JZLi7YaoiTpLCrc',
    appId: '1:59202183466:ios:56daa36a7518c0fcf1be53',
    messagingSenderId: '59202183466',
    projectId: 'proyect-desfc',
    storageBucket: 'proyect-desfc.firebasestorage.app',
    iosBundleId: 'com.example.projectDesarrolladoresfc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6R_JsaJ8Tl1OjFXb8zZlGKT5gjaWSIgc',
    appId: '1:59202183466:web:381ef9c30bac6b0cf1be53',
    messagingSenderId: '59202183466',
    projectId: 'proyect-desfc',
    authDomain: 'proyect-desfc.firebaseapp.com',
    storageBucket: 'proyect-desfc.firebasestorage.app',
    measurementId: 'G-1TX8RQ3V8D',
  );

}